### ISSUE TITLE
Participation in repo

### ISSUE THREAD

**Issue by fardad-dev** [amannn/atom-format-javascript-comment#10]
Hi dear

Few contributors and i developed a package for formatting comment.
https://github.com/hosseinmd/prettier-plugin-jsdoc
Your package is great but not developed for a long time. We're developing our package every day, but still need to help and introducing it.
We need more contributor/member for our package, I need your help. 

Thanks,
Best regards
Hossein

**Comment by amannn** [comment]
Hi Hossein,

thanks for reaching out! Your plugin definitely looks interesting and I'd be really interested in using it as part of a Prettier tool chain. However currently I'm quite limited on time and do not have the availability to take on new projects.

Thanks anyway for asking!
